<?php

namespace Database\Seeders;

use App\Models\WasteItem;
use Illuminate\Database\Seeder;

/**
 * Katalog lengkap klasifikasi sampah — 100 item.
 * Kategori: organik / anorganik / b3.
 * Sumber: rumah / kebun / tani / usaha / bengkel.
 */
class WasteItemSeeder extends Seeder
{
    public function run(): void
    {
        WasteItem::truncate();

        $data = [
            ['nama'=>'Kulit pisang','emoji'=>'🍌','kategori'=>'organik','sumber'=>'rumah','saran'=>'Pakan maggot / kompos','waktu_urai'=>'2–10 minggu','fakta'=>'Kulit pisang bisa jadi pengkilap sepatu dan pupuk penyubur tanaman!','urutan'=>1],
            ['nama'=>'Botol plastik','emoji'=>'🍼','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung ke Bank Sampah','waktu_urai'=>'± 450 tahun','fakta'=>'Satu botol plastik butuh ratusan tahun untuk hancur. Lebih tua dari kakek buyutmu!','urutan'=>2],
            ['nama'=>'Sisa sayur','emoji'=>'🥬','kategori'=>'organik','sumber'=>'rumah','saran'=>'POC / pakan maggot','waktu_urai'=>'1–2 minggu','fakta'=>'Sisa sayur cepat busuk, jadi bahan pupuk cair yang bagus untuk kebun.','urutan'=>3],
            ['nama'=>'Kaleng minuman','emoji'=>'🥫','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung — nilai jual tinggi','waktu_urai'=>'80–200 tahun','fakta'=>'Kaleng aluminium bisa didaur ulang berkali-kali tanpa kehilangan kualitas.','urutan'=>4],
            ['nama'=>'Daun kering','emoji'=>'🍂','kategori'=>'organik','sumber'=>'kebun','saran'=>'Bahan kompos','waktu_urai'=>'6 bulan–1 tahun','fakta'=>'Tumpukan daun kering adalah "emas coklat" untuk membuat kompos.','urutan'=>5],
            ['nama'=>'Kardus bekas','emoji'=>'📦','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Dilipat rapi, ditabung','waktu_urai'=>'± 2 bulan','fakta'=>'Kardus terbuat dari kertas, jadi lebih cepat terurai daripada plastik.','urutan'=>6],
            ['nama'=>'Sisa nasi','emoji'=>'🍚','kategori'=>'organik','sumber'=>'rumah','saran'=>'Pakan maggot','waktu_urai'=>'± 1 minggu','fakta'=>'Sisa nasi adalah menu favorit maggot untuk tumbuh gemuk.','urutan'=>7],
            ['nama'=>'Kantong kresek','emoji'=>'🛍️','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Kumpulkan, jangan dibakar','waktu_urai'=>'10–20 tahun','fakta'=>'Kresek yang dibakar menghasilkan asap beracun. Kumpulkan saja, ya!','urutan'=>8],
            ['nama'=>'Kulit buah','emoji'=>'🍊','kategori'=>'organik','sumber'=>'rumah','saran'=>'Fermentasi eco enzyme / POC','waktu_urai'=>'2–5 minggu','fakta'=>'Kulit jeruk dan nanas bisa disulap jadi cairan pembersih alami (eco enzyme).','urutan'=>9],
            ['nama'=>'Botol kaca','emoji'=>'🫙','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung / dipakai ulang','waktu_urai'=>'hampir selamanya','fakta'=>'Kaca hampir tidak pernah terurai, tapi bisa dipakai ulang selamanya!','urutan'=>10],
            ['nama'=>'Cangkang telur','emoji'=>'🥚','kategori'=>'organik','sumber'=>'rumah','saran'=>'Ditumbuk untuk pupuk','waktu_urai'=>'beberapa bulan','fakta'=>'Cangkang telur ditumbuk kaya kalsium, bikin tanaman lebih kuat.','urutan'=>11],
            ['nama'=>'Gelas plastik','emoji'=>'🥤','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Dibilas, ditabung','waktu_urai'=>'± 450 tahun','fakta'=>'Bawa botol minum sendiri bisa mengurangi tumpukan gelas plastik.','urutan'=>12],
            ['nama'=>'Ampas kelapa','emoji'=>'🥥','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos / pakan ternak','waktu_urai'=>'1–3 bulan','fakta'=>'Ampas kelapa bisa jadi pakan ayam atau bahan kompos yang subur.','urutan'=>13],
            ['nama'=>'Kertas bekas','emoji'=>'📄','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung ke Bank Sampah','waktu_urai'=>'2–6 minggu','fakta'=>'Mendaur ulang kertas menyelamatkan pohon dari ditebang.','urutan'=>14],
            ['nama'=>'Tulang ikan','emoji'=>'🐟','kategori'=>'organik','sumber'=>'rumah','saran'=>'Ditanam / kompos','waktu_urai'=>'beberapa bulan','fakta'=>'Tulang ikan mengandung fosfor yang bagus untuk menyuburkan tanah.','urutan'=>15],
            ['nama'=>'Styrofoam','emoji'=>'🍱','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Kurangi pemakaiannya!','waktu_urai'=>'500+ tahun','fakta'=>'Styrofoam sangat sulit hancur. Pilih wadah yang bisa dipakai ulang.','urutan'=>16],
            ['nama'=>'Eceng gondok','emoji'=>'🌿','kategori'=>'organik','sumber'=>'kebun','saran'=>'Dicacah jadi pakan ternak','waktu_urai'=>'beberapa minggu','fakta'=>'Eceng gondok yang mengganggu irigasi bisa disulap jadi pakan ternak murah.','urutan'=>17],
            ['nama'=>'Tutup botol','emoji'=>'🔘','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Kumpulkan, bisa jadi kerajinan','waktu_urai'=>'100+ tahun','fakta'=>'Ribuan tutup botol bisa dirangkai jadi mozaik atau kerajinan keren.','urutan'=>18],
            ['nama'=>'Ampas kopi','emoji'=>'☕','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos / pengusir hama','waktu_urai'=>'3–4 minggu','fakta'=>'Ampas kopi bisa mengusir semut dan menghilangkan bau di kulkas.','urutan'=>19],
            ['nama'=>'Roti basi','emoji'=>'🍞','kategori'=>'organik','sumber'=>'rumah','saran'=>'Pakan maggot','waktu_urai'=>'1–2 minggu','fakta'=>'Roti basi jangan dibuang sembarangan — jadikan pakan maggot!','urutan'=>20],
            ['nama'=>'Koran bekas','emoji'=>'📰','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung / bungkus','waktu_urai'=>'± 6 minggu','fakta'=>'Koran bekas bisa jadi pot tanaman atau kertas daur ulang.','urutan'=>21],
            ['nama'=>'Sedotan plastik','emoji'=>'🥤','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Kurangi, kumpulkan','waktu_urai'=>'± 200 tahun','fakta'=>'Sedotan kecil tapi bahaya untuk hewan laut. Coba sedotan bambu!','urutan'=>22],
            ['nama'=>'Kulit bawang','emoji'=>'🧅','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos / pewarna alami','waktu_urai'=>'1–2 minggu','fakta'=>'Kulit bawang bisa jadi pewarna alami kain berwarna coklat keemasan.','urutan'=>23],
            ['nama'=>'Botol sampo','emoji'=>'🧴','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Dibilas, ditabung','waktu_urai'=>'± 450 tahun','fakta'=>'Bilas dulu botol sampo sebelum ditabung agar tidak berbau.','urutan'=>24],
            ['nama'=>'Rumput & gulma','emoji'=>'🌱','kategori'=>'organik','sumber'=>'kebun','saran'=>'Kompos / pakan ternak','waktu_urai'=>'2–4 minggu','fakta'=>'Rumput hasil potongan bisa langsung jadi bahan kompos hijau.','urutan'=>25],
            ['nama'=>'Sachet plastik','emoji'=>'🧃','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Kumpulkan, jangan dibakar','waktu_urai'=>'puluhan tahun','fakta'=>'Sachet berlapis sulit didaur ulang — kurangi beli produk sachet.','urutan'=>26],
            ['nama'=>'Ranting kayu','emoji'=>'🪵','kategori'=>'organik','sumber'=>'kebun','saran'=>'Kompos / mulsa','waktu_urai'=>'beberapa bulan','fakta'=>'Ranting bisa dicacah jadi mulsa penahan air di sekitar tanaman.','urutan'=>27],
            ['nama'=>'Pecahan beling','emoji'=>'🔪','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Bungkus aman sebelum dibuang','waktu_urai'=>'hampir selamanya','fakta'=>'Bungkus pecahan kaca dengan kertas tebal agar tidak melukai petugas.','urutan'=>28],
            ['nama'=>'Kulit udang','emoji'=>'🦐','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos / pupuk','waktu_urai'=>'beberapa minggu','fakta'=>'Kulit udang kaya zat kitin yang bagus untuk kesehatan tanah.','urutan'=>29],
            ['nama'=>'Tutup kaleng','emoji'=>'🥫','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Logam — nilai jual tinggi','waktu_urai'=>'80+ tahun','fakta'=>'Logam punya harga jual paling tinggi di Bank Sampah!','urutan'=>30],
            ['nama'=>'Teh celup bekas','emoji'=>'🍵','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos','waktu_urai'=>'beberapa minggu','fakta'=>'Teh celup bekas bisa menyegarkan tanah dan mengusir bau.','urutan'=>31],
            ['nama'=>'Kabel bekas','emoji'=>'🔌','kategori'=>'anorganik','sumber'=>'bengkel','saran'=>'Pisahkan, jangan dibakar','waktu_urai'=>'puluhan tahun','fakta'=>'Tembaga di dalam kabel bernilai jual — jangan dibakar, berbahaya!','urutan'=>32],
            ['nama'=>'Baterai bekas','emoji'=>'🔋','kategori'=>'b3','sumber'=>'rumah','saran'=>'Kumpulkan terpisah, serahkan ke dropbox B3','waktu_urai'=>'ratusan tahun','fakta'=>'Baterai mengandung logam berat (merkuri, kadmium) yang meracuni tanah & air.','urutan'=>33],
            ['nama'=>'Lampu bekas','emoji'=>'💡','kategori'=>'b3','sumber'=>'rumah','saran'=>'Bungkus aman, jangan dibuang ke sampah biasa','waktu_urai'=>'tidak terurai','fakta'=>'Lampu neon/LED mengandung merkuri; bila pecah uapnya berbahaya.','urutan'=>34],
            ['nama'=>'Aki bekas','emoji'=>'🪫','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Serahkan ke pengepul resmi/bengkel','waktu_urai'=>'sangat lama','fakta'=>'Aki berisi asam & timbal — punya nilai jual tapi wajib ditangani khusus.','urutan'=>35],
            ['nama'=>'Obat kadaluarsa','emoji'=>'💊','kategori'=>'b3','sumber'=>'rumah','saran'=>'Rusak kemasan, serahkan ke puskesmas/apotek','waktu_urai'=>'bervariasi','fakta'=>'Obat dibuang sembarangan mencemari air & bisa disalahgunakan.','urutan'=>36],
            ['nama'=>'Kaleng aerosol','emoji'=>'🧴','kategori'=>'b3','sumber'=>'rumah','saran'=>'Pastikan kosong, kumpulkan terpisah','waktu_urai'=>'ratusan tahun','fakta'=>'Sisa gas bertekanan bisa meledak bila terkena panas atau dibakar.','urutan'=>37],
            ['nama'=>'Oli bekas','emoji'=>'🛢️','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Tampung di wadah, serahkan ke pengumpul oli','waktu_urai'=>'mencemari lama','fakta'=>'1 liter oli bekas dapat mencemari ribuan liter air bersih.','urutan'=>38],
            ['nama'=>'Elektronik rusak','emoji'=>'📱','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Kumpulkan sebagai e-waste','waktu_urai'=>'ratusan tahun','fakta'=>'HP & gadget rusak (e-waste) mengandung logam berat sekaligus logam berharga.','urutan'=>39],
            ['nama'=>'Cat & tiner bekas','emoji'=>'🎨','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Tutup rapat, jangan dibuang ke saluran air','waktu_urai'=>'mencemari lama','fakta'=>'Bahan kimia cat & tiner beracun bagi tanah, air, dan pernapasan.','urutan'=>40],
            ['nama'=>'Minyak jelantah','emoji'=>'🛢️','kategori'=>'b3','sumber'=>'rumah','saran'=>'Kumpulkan di botol tertutup, setor/jual ke pengepul — jangan buang ke got','waktu_urai'=>'mencemari air puluhan tahun','fakta'=>'Satu liter jelantah dapat mencemari ribuan liter air bersih.','urutan'=>41],
            ['nama'=>'Tulang ayam & daging','emoji'=>'🍗','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kubur atau kompos lambat — jangan dibiarkan terbuka','waktu_urai'=>'beberapa bulan – tahunan','fakta'=>'Sisa daging terbuka mengundang tikus & lalat — sumber leptospirosis dan diare.','urutan'=>42],
            ['nama'=>'Kain perca & baju bekas','emoji'=>'👕','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Donasikan, atau daur ulang jadi lap & kerajinan','waktu_urai'=>'puluhan–ratusan tahun','fakta'=>'Industri tekstil termasuk penyumbang limbah terbesar dunia — pakai ulang lebih baik.','urutan'=>43],
            ['nama'=>'Popok & pembalut bekas','emoji'=>'🧷','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Bungkus rapat, buang ke tempat sampah residu — jangan ke sungai','waktu_urai'=>'± 500 tahun','fakta'=>'Popok sekali pakai adalah salah satu sampah terbanyak yang ditemukan di sungai Indonesia.','urutan'=>44],
            ['nama'=>'Kosmetik kedaluwarsa','emoji'=>'💄','kategori'=>'b3','sumber'=>'rumah','saran'=>'Serahkan ke dropbox B3 — jangan dicampur sampah biasa','waktu_urai'=>'tidak terurai alami','fakta'=>'Kosmetik kedaluwarsa bisa mengandung bahan kimia yang mengiritasi kulit dan mencemari air.','urutan'=>45],
            ['nama'=>'Sisa pembersih lantai','emoji'=>'🧴','kategori'=>'b3','sumber'=>'rumah','saran'=>'Habiskan sesuai takaran; kemasan dibilas 2x sebelum dibuang / setor B3','waktu_urai'=>'tidak terurai alami','fakta'=>'Cairan pembersih keras dapat menyebabkan iritasi mata parah hingga luka bakar kulit.','urutan'=>46],
            ['nama'=>'Puntung rokok','emoji'=>'🚬','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Matikan sempurna, buang ke tempat sampah residu — jangan dibuang sembarangan','waktu_urai'=>'10–12 tahun','fakta'=>'Puntung rokok adalah sampah paling banyak ditemukan di dunia dan mengandung mikroplastik.','urutan'=>47],
            ['nama'=>'Masker sekali pakai','emoji'=>'😷','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Gunting talinya, bungkus, buang ke residu','waktu_urai'=>'± 450 tahun','fakta'=>'Tali masker yang tidak digunting sering menjerat burung dan satwa air.','urutan'=>48],
            ['nama'=>'Ember & galon pecah','emoji'=>'🏺','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Ditabung ke Bank Sampah — plastik keras bernilai jual','waktu_urai'=>'± 450 tahun','fakta'=>'Plastik keras (HDPE) termasuk yang paling laku di pengepul.','urutan'=>49],
            ['nama'=>'Kemasan karton minuman','emoji'=>'🧃','kategori'=>'anorganik','sumber'=>'usaha','saran'=>'Bilas, keringkan, lipat, tabung ke Bank Sampah','waktu_urai'=>'puluhan tahun','fakta'=>'Kemasan tetrapak berlapis kertas-plastik-aluminium sehingga butuh daur ulang khusus.','urutan'=>50],
            ['nama'=>'Cangkang kerang','emoji'=>'🐚','kategori'=>'organik','sumber'=>'usaha','saran'=>'Bahan kerajinan / dihancurkan jadi campuran pakan & kapur','waktu_urai'=>'sangat lambat','fakta'=>'Cangkang kerang kaya kalsium — bisa jadi campuran pakan ternak setelah dihaluskan.','urutan'=>51],
            ['nama'=>'Jerami & sekam padi','emoji'=>'🌾','kategori'=>'organik','sumber'=>'tani','saran'=>'Kompos, mulsa, atau media tanam — jangan dibakar','waktu_urai'=>'beberapa bulan','fakta'=>'Membakar jerami menyumbang polusi udara dan memicu ISPA — padahal nilainya tinggi untuk tanah.','urutan'=>52],
            ['nama'=>'Kulit jagung & bonggol','emoji'=>'🌽','kategori'=>'organik','sumber'=>'tani','saran'=>'Pakan ternak / kompos / bahan kerajinan','waktu_urai'=>'beberapa bulan','fakta'=>'Kulit jagung kering bisa dianyam jadi kerajinan bernilai jual.','urutan'=>53],
            ['nama'=>'Kotoran ternak','emoji'=>'🐐','kategori'=>'organik','sumber'=>'tani','saran'=>'Olah jadi pupuk kandang atau biogas','waktu_urai'=>'beberapa minggu','fakta'=>'Kotoran ternak yang diolah benar adalah pupuk terbaik untuk sawah dan kebun.','urutan'=>54],
            ['nama'=>'Kemasan pestisida','emoji'=>'🧪','kategori'=>'b3','sumber'=>'tani','saran'=>'Bilas 3x, rusak kemasannya, serahkan ke fasilitas B3 — jangan dipakai ulang','waktu_urai'=>'tidak terurai alami','fakta'=>'Kemasan pestisida bekas sangat berbahaya jika dipakai ulang untuk wadah makanan/minuman.','urutan'=>55],
            ['nama'=>'Ban bekas','emoji'=>'⭕','kategori'=>'anorganik','sumber'=>'bengkel','saran'=>'Setor ke pengepul, atau manfaatkan jadi pot & ayunan','waktu_urai'=>'ratusan tahun','fakta'=>'Ban bekas yang menampung air hujan jadi sarang nyamuk DBD — jangan dibiarkan terbuka.','urutan'=>56],
            ['nama'=>'Kulit kentang & umbi','emoji'=>'🥔','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos atau bahan POC','waktu_urai'=>'1–2 minggu','fakta'=>'Kulit kentang mengandung nutrisi tinggi untuk pupuk cair.','urutan'=>57],
            ['nama'=>'Biji & pit buah','emoji'=>'🥭','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos lambat, atau semai jadi bibit tanaman','waktu_urai'=>'beberapa bulan','fakta'=>'Biji mangga dan alpukat bisa disemai jadi bibit — sampah jadi pohon!','urutan'=>58],
            ['nama'=>'Sisa makanan berkuah','emoji'=>'🍲','kategori'=>'organik','sumber'=>'rumah','saran'=>'Tiriskan kuahnya dulu, ampasnya untuk pakan maggot/kompos','waktu_urai'=>'beberapa hari','fakta'=>'Kuah yang dibuang langsung ke kompos membuatnya becek dan bau — tiriskan dahulu.','urutan'=>59],
            ['nama'=>'Kulit kacang','emoji'=>'🥜','kategori'=>'organik','sumber'=>'rumah','saran'=>'Kompos atau mulsa penutup tanah','waktu_urai'=>'± 1 tahun','fakta'=>'Kulit kacang terurai lambat — cocok jadi mulsa penahan gulma.','urutan'=>60],
            ['nama'=>'Sabut & batok kelapa','emoji'=>'🥥','kategori'=>'organik','sumber'=>'rumah','saran'=>'Arang batok, kerajinan, atau media tanam (cocopeat)','waktu_urai'=>'± 1 tahun','fakta'=>'Batok kelapa bisa jadi arang briket bernilai jual; sabutnya jadi media tanam.','urutan'=>61],
            ['nama'=>'Bunga & tanaman layu','emoji'=>'💐','kategori'=>'organik','sumber'=>'kebun','saran'=>'Kompos atau eco-enzyme','waktu_urai'=>'1–2 minggu','fakta'=>'Bunga layu cepat terurai dan membuat kompos harum.','urutan'=>62],
            ['nama'=>'Buah jatuh membusuk','emoji'=>'🍎','kategori'=>'organik','sumber'=>'kebun','saran'=>'Segera kompos / pakan maggot — jangan dibiarkan','waktu_urai'=>'beberapa hari','fakta'=>'Buah busuk yang dibiarkan mengundang lalat buah yang merusak panen berikutnya.','urutan'=>63],
            ['nama'=>'Pelepah & daun pisang','emoji'=>'🍌','kategori'=>'organik','sumber'=>'kebun','saran'=>'Pembungkus alami, pakan ternak, atau kompos','waktu_urai'=>'2–4 minggu','fakta'=>'Daun pisang adalah pembungkus makanan alami pengganti plastik & styrofoam.','urutan'=>64],
            ['nama'=>'Batang & daun singkong','emoji'=>'🌱','kategori'=>'organik','sumber'=>'tani','saran'=>'Daunnya sayur/pakan ternak; batangnya bibit stek','waktu_urai'=>'beberapa minggu','fakta'=>'Satu batang singkong bisa jadi puluhan bibit stek baru.','urutan'=>65],
            ['nama'=>'Keong sawah','emoji'=>'🐌','kategori'=>'organik','sumber'=>'tani','saran'=>'Rebus untuk pakan bebek/ternak — bagian dari program pakan murah','waktu_urai'=>'cepat','fakta'=>'Keong sawah dicacah + eceng gondok = pakan ternak murah program KKN Pajaten!','urutan'=>66],
            ['nama'=>'Tusuk sate & bambu bekas','emoji'=>'🍢','kategori'=>'organik','sumber'=>'usaha','saran'=>'Patahkan ujung tajamnya, kompos lambat atau bahan kerajinan','waktu_urai'=>'1–3 tahun','fakta'=>'Ujung tusuk sate yang tajam berbahaya bagi petugas sampah — selalu patahkan dulu.','urutan'=>67],
            ['nama'=>'Daun pembungkus makanan','emoji'=>'🍃','kategori'=>'organik','sumber'=>'usaha','saran'=>'Kompos — cepat terurai','waktu_urai'=>'1–2 minggu','fakta'=>'Beralih ke daun pembungkus mengurangi sampah plastik warung secara drastis.','urutan'=>68],
            ['nama'=>'Ampas tahu & tempe','emoji'=>'🥘','kategori'=>'organik','sumber'=>'usaha','saran'=>'Pakan ternak / maggot — bernilai jual','waktu_urai'=>'beberapa hari','fakta'=>'Ampas tahu adalah pakan ternak favorit — banyak dicari peternak.','urutan'=>69],
            ['nama'=>'Sisa ikan & jeroan','emoji'=>'🐟','kategori'=>'organik','sumber'=>'usaha','saran'=>'Pakan maggot atau kubur — olah cepat karena bau','waktu_urai'=>'beberapa hari','fakta'=>'Jeroan ikan adalah pakan maggot BSF terbaik — maggot tumbuh 2x lebih cepat.','urutan'=>70],
            ['nama'=>'Serbuk gergaji','emoji'=>'🌲','kategori'=>'organik','sumber'=>'bengkel','saran'=>'Media jamur tiram, alas kandang, atau campuran kompos','waktu_urai'=>'beberapa bulan','fakta'=>'Serbuk gergaji adalah media tanam jamur tiram — peluang usaha rumahan.','urutan'=>71],
            ['nama'=>'Sikat gigi bekas','emoji'=>'🦷','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Buang ke residu — atau pakai ulang untuk sikat pembersih','waktu_urai'=>'± 500 tahun','fakta'=>'Sikat gigi bekas sulit didaur ulang karena gabungan plastik & nilon.','urutan'=>72],
            ['nama'=>'Spons & sabut cuci piring','emoji'=>'🧽','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Buang ke residu setelah benar-benar rusak','waktu_urai'=>'ratusan tahun','fakta'=>'Spons melepas mikroplastik — ganti dengan sabut kelapa alami lebih ramah.','urutan'=>73],
            ['nama'=>'Mainan plastik rusak','emoji'=>'🧸','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Donasikan jika masih layak; jika rusak total, tabung plastik keras','waktu_urai'=>'ratusan tahun','fakta'=>'Perbaiki atau donasikan dulu — banyak mainan hanya rusak kecil.','urutan'=>74],
            ['nama'=>'Pulpen & spidol habis','emoji'=>'🖊️','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Buang ke residu — pilih pulpen isi ulang ke depannya','waktu_urai'=>'ratusan tahun','fakta'=>'Miliaran pulpen sekali pakai dibuang tiap tahun — pulpen isi ulang jauh lebih hemat.','urutan'=>75],
            ['nama'=>'Sepatu & sandal bekas','emoji'=>'👟','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Donasikan, perbaiki, atau setor ke bank sampah','waktu_urai'=>'puluhan–ratusan tahun','fakta'=>'Sandal jepit bekas bisa didaur jadi kerajinan dan alas bermain.','urutan'=>76],
            ['nama'=>'Buku & majalah bekas','emoji'=>'📚','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Donasikan ke taman baca, atau tabung sebagai kertas','waktu_urai'=>'2–6 minggu (kertas)','fakta'=>'Buku bekas layak baca lebih berharga didonasikan daripada dikilo.','urutan'=>77],
            ['nama'=>'Kaset, CD & DVD bekas','emoji'=>'💿','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Bahan kerajinan (hiasan pengusir burung) atau residu','waktu_urai'=>'ratusan tahun','fakta'=>'Kepingan CD bekas efektif jadi pengusir burung di sawah.','urutan'=>78],
            ['nama'=>'Tisu & kertas minyak','emoji'=>'🧻','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Buang ke residu — kertas terkena minyak tidak bisa didaur ulang','waktu_urai'=>'beberapa minggu–bulan','fakta'=>'Kertas yang terkontaminasi minyak/makanan tidak diterima pendaur ulang.','urutan'=>79],
            ['nama'=>'Botol kecap & saus kaca','emoji'=>'🍶','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Pakai ulang sebagai wadah, atau tabung kaca ke Bank Sampah','waktu_urai'=>'± 1 juta tahun','fakta'=>'Kaca bisa didaur ulang tanpa batas tanpa menurun kualitasnya.','urutan'=>80],
            ['nama'=>'Cermin & kaca pecah','emoji'=>'🖼️','kategori'=>'anorganik','sumber'=>'rumah','saran'=>'Bungkus tebal dengan kertas/kardus, beri label, buang ke residu','waktu_urai'=>'± 1 juta tahun','fakta'=>'Kaca pecah tanpa pembungkus melukai petugas sampah — selalu bungkus dan beri tulisan.','urutan'=>81],
            ['nama'=>'Cup kopi & minuman kekinian','emoji'=>'☕','kategori'=>'anorganik','sumber'=>'usaha','saran'=>'Bilas, tabung ke Bank Sampah; sedotannya ke residu','waktu_urai'=>'± 450 tahun','fakta'=>'Tren minuman kekinian menambah jutaan cup plastik per hari di Indonesia.','urutan'=>82],
            ['nama'=>'Plastik es & bungkus bening','emoji'=>'🧊','kategori'=>'anorganik','sumber'=>'usaha','saran'=>'Kumpulkan bersih & kering, tabung ke Bank Sampah','waktu_urai'=>'ratusan tahun','fakta'=>'Plastik bening bersih (PP) punya nilai jual lebih tinggi daripada yang kotor.','urutan'=>83],
            ['nama'=>'Karung beras & pupuk','emoji'=>'🧺','kategori'=>'anorganik','sumber'=>'tani','saran'=>'Pakai ulang berkali-kali, atau tabung ke pengepul','waktu_urai'=>'puluhan tahun','fakta'=>'Karung bekas kuat dipakai ulang bertahun-tahun untuk panen dan angkut.','urutan'=>84],
            ['nama'=>'Tali rafia & jaring','emoji'=>'🧵','kategori'=>'anorganik','sumber'=>'tani','saran'=>'Kumpulkan dan setor — jangan dibakar atau dibiarkan di sawah','waktu_urai'=>'ratusan tahun','fakta'=>'Sisa rafia di lahan terlilit di bajak dan membahayakan ternak yang memakannya.','urutan'=>85],
            ['nama'=>'Mulsa plastik bekas','emoji'=>'🎞️','kategori'=>'anorganik','sumber'=>'tani','saran'=>'Bersihkan dari tanah, gulung, setor ke pengepul plastik','waktu_urai'=>'ratusan tahun','fakta'=>'Mulsa yang dibenamkan ke tanah merusak kesuburan bertahun-tahun.','urutan'=>86],
            ['nama'=>'Seng & besi bekas','emoji'=>'🔩','kategori'=>'anorganik','sumber'=>'bengkel','saran'=>'Setor ke rongsok — logam bernilai jual tinggi','waktu_urai'=>'puluhan–ratusan tahun','fakta'=>'Besi bekas adalah komoditas rongsok paling stabil harganya.','urutan'=>87],
            ['nama'=>'Pipa PVC & selang bekas','emoji'=>'🚿','kategori'=>'anorganik','sumber'=>'bengkel','saran'=>'Potongan panjang bisa dipakai ulang; sisanya setor pengepul','waktu_urai'=>'ratusan tahun','fakta'=>'Pipa bekas sering bisa dipakai ulang untuk irigasi tetes sederhana.','urutan'=>88],
            ['nama'=>'Keramik & genteng pecah','emoji'=>'🧱','kategori'=>'anorganik','sumber'=>'bengkel','saran'=>'Manfaatkan untuk urugan/jalan setapak — jangan buang ke sungai','waktu_urai'=>'tidak terurai','fakta'=>'Pecahan genteng bagus untuk dasar pot agar air tidak menggenang.','urutan'=>89],
            ['nama'=>'Sisa pemutih pakaian','emoji'=>'🥼','kategori'=>'b3','sumber'=>'rumah','saran'=>'Habiskan sesuai takaran; jangan campur dengan pembersih lain','waktu_urai'=>'tidak terurai alami','fakta'=>'Mencampur pemutih dengan pembersih lain dapat menghasilkan gas klorin beracun!','urutan'=>90],
            ['nama'=>'Racun tikus & serangga','emoji'=>'🐀','kategori'=>'b3','sumber'=>'rumah','saran'=>'Simpan jauh dari anak & pangan; sisa/kemasan serahkan ke B3','waktu_urai'=>'tidak terurai alami','fakta'=>'Kemasan racun yang dibuang sembarangan sering termakan ternak dan hewan peliharaan.','urutan'=>91],
            ['nama'=>'Obat nyamuk & kapur barus','emoji'=>'🦟','kategori'=>'b3','sumber'=>'rumah','saran'=>'Habiskan, kemasannya ke residu; jangan dibakar bersama sampah','waktu_urai'=>'lambat','fakta'=>'Membakar sisa obat nyamuk melepaskan zat kimia berbahaya ke udara.','urutan'=>92],
            ['nama'=>'Jarum & alat medis rumahan','emoji'=>'💉','kategori'=>'b3','sumber'=>'rumah','saran'=>'Masukkan wadah keras tertutup (botol bekas), serahkan ke puskesmas','waktu_urai'=>'tidak terurai','fakta'=>'Jarum lepas di kantong sampah adalah risiko tertusuk & infeksi bagi petugas.','urutan'=>93],
            ['nama'=>'Termometer & barang merkuri','emoji'=>'🌡️','kategori'=>'b3','sumber'=>'rumah','saran'=>'Jangan dipecah! Serahkan utuh ke fasilitas B3/puskesmas','waktu_urai'=>'tidak terurai','fakta'=>'Merkuri dari satu termometer bisa mencemari air satu kolam.','urutan'=>94],
            ['nama'=>'Hand sanitizer kedaluwarsa','emoji'=>'🧴','kategori'=>'b3','sumber'=>'rumah','saran'=>'Jangan dibakar (mudah terbakar); serahkan ke dropbox B3','waktu_urai'=>'tidak terurai alami','fakta'=>'Kandungan alkohol tinggi membuatnya mudah terbakar — jauhkan dari api.','urutan'=>95],
            ['nama'=>'Powerbank & baterai HP','emoji'=>'🔋','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Serahkan ke dropbox B3/toko elektronik — jangan ditusuk atau dibakar','waktu_urai'=>'tidak terurai','fakta'=>'Baterai lithium yang rusak bisa meledak dan memicu kebakaran di truk sampah.','urutan'=>96],
            ['nama'=>'Tinta & toner printer','emoji'=>'🖨️','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Kembalikan ke toko/refill; jangan dibuang ke tanah','waktu_urai'=>'tidak terurai','fakta'=>'Satu cartridge butuh ±3 liter minyak bumi untuk dibuat — isi ulang lebih hemat.','urutan'=>97],
            ['nama'=>'Minyak rem & cairan radiator','emoji'=>'🚗','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Tampung terpisah, serahkan ke pengelola limbah B3','waktu_urai'=>'mencemari air & tanah','fakta'=>'Cairan radiator manis rasanya bagi hewan — namun sangat beracun.','urutan'=>98],
            ['nama'=>'Filter oli bekas','emoji'=>'⚙️','kategori'=>'b3','sumber'=>'bengkel','saran'=>'Tiriskan olinya, kumpulkan bersama limbah B3 bengkel','waktu_urai'=>'tidak terurai','fakta'=>'Satu filter oli bekas masih menyimpan sisa oli yang mencemari tanah.','urutan'=>99],
            ['nama'=>'Sisa pupuk kimia','emoji'=>'🧫','kategori'=>'b3','sumber'=>'tani','saran'=>'Simpan kering & tertutup; kemasan kosong jangan untuk wadah pangan','waktu_urai'=>'mencemari air tanah','fakta'=>'Pupuk kimia berlebih yang terbawa hujan menyuburkan gulma air & merusak sungai.','urutan'=>100],
        ];

        foreach ($data as $row) {
            WasteItem::create($row);
        }
    }
}
